language: python
sudo: false
bundler_args: --retry 3

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8


before_install:
  - pip install --upgrade pip

install:
  - pip install zc.buildout
  - travis_retry buildout -c testing.cfg

script:
  - travis_retry bin/py setup.py test -q
